### ISSUE TITLE
Binding for ElementHandle.contentFrame()

### ISSUE THREAD

**Issue by zploskey** [bs-puppeteer/bs-puppeteer#23]
This should be included in Puppeteer 1.2.0 which is expected to be released on March 15th.

[Docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlecontentframe)

**Comment by jihchi** [comment]
I'm trying to make this binding, but I got `dependency cycle` error from following code (`src/ElementHandle.re`):
```ml
[@bs.send.pipe: t]
external contentFrame : unit => Js.Promise.t(Js.Nullable.t(Frame.t)) = "";
```

error message:
```
ninja: error: dependency cycle: src/Frame-BsPuppeteer.cmj -> src/FrameBase-BsPuppeteer.cmj -> src/ElementHandle-BsPuppeteer.cmj -> src/Frame-BsPuppeteer.cmj
```

Do you have any idea how to avoid this error?

**Comment by zploskey** [comment]
Whenever I have run into a dependency cycle I have started abstracting the types out into another module. I've just been putting them in `Types.re`. If you can't get rid of the cycle using what's there then you can add another type in that file.

**Comment by jihchi** [comment]
Thanks!
