### ISSUE TITLE
Remove use of bs.send.pipe

### ISSUE THREAD

**Issue by zploskey** [bs-puppeteer/bs-puppeteer#36]
Hopefully we can do this once type-first pipe syntax with `|.` lands in BuckleScript. Then we'll have to do a release that changes all `bs.send.pipe` annotations to `bs.send` with `t` in the first position and include instructions to change the pipe operator to `|.` instead of `|>` in code calling our library functions.

**Comment by jihchi** [comment]
Related: https://github.com/BuckleScript/bucklescript/issues/2625

**Comment by zploskey** [comment]
The t-first pipe syntax using `|.` landed in BuckleScript [2.2.3](https://github.com/BuckleScript/bucklescript/blob/master/Changes.md#223). Probably better to make this change sooner rather than later when we have more dependent projects.

**Comment by zploskey** [comment]
I'm actually still on the fence about whether there is much significant benefit from using `bs.deriving abstract` over `bs.obj`. It doesn't support many of the features we're using like `bs.string` and is more verbose for optional fields of which we have a ton with all of these options objects. It also usually necessitates wrapping the object's type in a module to contain all the generated accessors. It sounds like `bs.obj`  is no longer in danger of going away, so I now think that we should continue to use `bs.obj` for binding to javascript objects.

That said, t-first style using fast pipe (now changed from `|.` to `->` in Reason since I opened this) does produce much better js output than `|>`. Moving forward with that part.
