### ISSUE TITLE
Write bindings for Page.pdf()

### ISSUE THREAD

**Issue by zploskey** [bs-puppeteer/bs-puppeteer#4]
`Page.pdf()` needs an implementation similar to other several other functions that take options objects, like `Puppeteer.launch()`. This would involve creating a type `Page.pdfOptions` and a `[@bs.obj]` annotated external `Page.makePDFOptions()`. Like the other examples already implemented, we'll wanted to create another function with the same name to shadow the external `Page.makePDFOptions`. It will convert to JS types--in particular `bool` needs to be converted to `Js.boolean`. We can use the helper functions in our `Util` module for that. 

[Docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions)

The [Typescript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/puppeteer/index.d.ts) are a good reference here. They list all the possible values of the string enum `pdfFormat` which we'll probably want to handle using `[@bs.string]`. Searching for "pdf" on that should lead to the relevant definitions.

Also, the Pdf module can be removed as we should just put this all in the Page module.

**Comment by jihchi** [comment]
I would like to take care this issue.
