### ISSUE TITLE
Selector functions for FrameBase

### ISSUE THREAD

**Issue by zploskey** [bs-puppeteer/bs-puppeteer#5]
Some of these functions have names we cannot use, containing `$`. Seems reasonable to call them variations of `select`. Other than necessary naming adjustments, we have more or less been following the typescript definitions. Some of these may already have stubs, but should be changed to use `[@bs.send.pipe : t]`.

Typescript definition --> suggested name
`$(selector: string): Promise<ElementHandle | null>;` --> `selectOne`
`$$(selector: string): Promise<ElementHandle[]>;` --> `selectAll`
```typescript
  waitForSelector(
    selector: string,
    options?: { visible?: boolean; hidden?: boolean; timeout?: number }
  ): Promise<ElementHandle>;
```
--> same name, options should be type selectorOptions created with a special creation function with all optional parameters.

Wouldn't be opposed to just calling these `querySelect` or `querySelector`, which is what it is calling in the frame/page.

References:
Typescript definitions: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/puppeteer/index.d.ts
API Documentation:
https://github.com/GoogleChrome/puppeteer/blob/v1.1.0/docs/api.md

NOTE: The page interface should have a different `select()` function, which checks `<options>`s in a `<select>`.

**Comment by jihchi** [comment]
This looks good to me!
```
page.$(..) --> page.selectOne(..)
page.$$(..) --> page.selectAll(..)
page.$$eval(..) --> page.selectAllEval(..)
page.$eval(..) --> page.selectOneEval(..)
```

**Comment by zploskey** [comment]
I think that feels right. I'll make the adjustments to the names.
