### ISSUE TITLE
Port over missing bindings from other repo

### ISSUE THREAD

**Issue by zploskey** [bs-puppeteer/bs-puppeteer#9]
@jihchi was independently working on some bindings at https://github.com/jihchi/bs-puppeteer-legacy. It makes sense to move over the ones we are missing here. Preferably we do this one feature at a time and give an opportunity to review the API choices before merging.

**Comment by jihchi** [comment]
I could move the test first.

**Comment by zploskey** [comment]
Sounds good to me.

**Comment by jihchi** [comment]
Some test has been merged in commit a3a9551f13e1219b0364082ce84a9506c5329f0e.
